<?php if (count($this->getGiftCards()) > 0): ?>
    <?php foreach($this->getGiftCards() as $card):?>
        <tr>
            <th colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>">
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                <div class="aw_giftcard2-total-description"><?php echo $this->__('Gift Card (%s)', $card->getCode()); ?></div>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
            </th>
            <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
                -<?php echo $this->helper('checkout')->formatPrice($card->getGiftcardAmount()) ?>
                <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
            </td>
        </tr>
    <?php endforeach;?>
<?php endif;?>