<div class="discount aw_giftcard2">
    <h2><?php echo $this->__('Gift Cards') ?></h2>
    <form id="aw_giftcard2-form" action="<?php echo $this->getFormUrl();?>" method="post">
        <fieldset>
            <label for="giftcard_code"><?php echo $this->__('Enter your gift card code') ?></label>
            <div class="input-box">
                <input class="required-entry input-text" id="giftcard_code" name="giftcard_code" value="" />
            </div>
            <div class="buttons-set">
                <button class="button" onclick="AwGiftcardForm.submit()" type="button" value="<?php echo $this->__('Apply Gift Card Code') ?>">
                    <span><span><?php echo $this->__('Apply Gift Card Code') ?></span></span>
                </button>
            </div>
        </fieldset>
    </form>
    <script type="text/javascript">
        var AwGiftcardForm = new VarienForm('aw_giftcard2-form');
    </script>
</div>